"""add cities, city_id on days, city_id and nullable day_id on stops

Revision ID: 36db9ab9fa52
Revises: c31f598df414
Create Date: 2026-09-27 18:40:39.428818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36db9ab9fa52'
down_revision: Union[str, Sequence[str], None] = 'c31f598df414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('days', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'days', 'cities', ['city_id'], ['id'])
    op.add_column('stops', sa.Column('city_id', sa.Integer(), nullable=True))
    op.alter_column('stops', 'day_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'stops', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###
    # Not autogenerated - alembic's autogenerate doesn't detect CHECK
    # constraints, so this has to be added by hand. Enforces the same
    # invariant as Stop.__table_args__ in models/stop.py: a stop belongs to
    # exactly one of a day or a city, never both, never neither.
    op.create_check_constraint(
        "ck_stop_exactly_one_parent",
        "stops",
        "(day_id IS NULL) != (city_id IS NULL)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_stop_exactly_one_parent", "stops", type_="check")
    op.drop_constraint(None, 'stops', type_='foreignkey')
    op.alter_column('stops', 'day_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('stops', 'city_id')
    op.drop_constraint(None, 'days', type_='foreignkey')
    op.drop_column('days', 'city_id')
    op.drop_table('cities')
    # ### end Alembic commands ###
