"""add first name last name avatar color to users

Revision ID: 64d99c8b985d
Revises: 76627f872f45
Create Date: 2026-08-16 16:41:57.179711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d99c8b985d'
down_revision: Union[str, Sequence[str], None] = '76627f872f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


AVATAR_COLORS = (
    "#ef4444", "#f97316", "#f59e0b", "#84cc16", "#22c55e", "#14b8a6",
    "#06b6d4", "#3b82f6", "#6366f1", "#8b5cf6", "#ec4899", "#f43f5e",
)


def upgrade() -> None:
    """Upgrade schema."""
    # Adjusted from the autogenerated version: adding NOT NULL columns
    # straight up would fail against this table's existing rows (this app
    # already has real signups), so add them nullable, backfill a value for
    # every existing row, then tighten to NOT NULL - existing users get a
    # throwaway placeholder name and a color cycled from the same palette
    # `update_avatar_color` validates against, both editable afterwards
    # (name isn't currently editable in the UI, but nothing stops it being
    # correct data either way).
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("avatar_color", sa.String(), nullable=True))

    op.execute("UPDATE users SET first_name = split_part(email, '@', 1) WHERE first_name IS NULL")
    op.execute("UPDATE users SET last_name = 'User' WHERE last_name IS NULL")
    colors_literal = "ARRAY[" + ", ".join(f"'{color}'" for color in AVATAR_COLORS) + "]"
    op.execute(
        f"UPDATE users SET avatar_color = ({colors_literal})[(id % {len(AVATAR_COLORS)}) + 1] "
        "WHERE avatar_color IS NULL"
    )

    op.alter_column("users", "first_name", nullable=False)
    op.alter_column("users", "last_name", nullable=False)
    op.alter_column("users", "avatar_color", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_color')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
