"""drop day order_index, add unique trip_id+date constraint

Revision ID: 76627f872f45
Revises: d25b1fde590a
Create Date: 2026-08-05 23:57:09.719474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76627f872f45'
down_revision: Union[str, Sequence[str], None] = 'd25b1fde590a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_day_trip_date', 'days', ['trip_id', 'date'])
    op.drop_column('days', 'order_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_day_trip_date', 'days', type_='unique')
    # ### end Alembic commands ###
