"""add is_important and is_optional to stops

Revision ID: 7c1d624af8be
Revises: 64d99c8b985d
Create Date: 2026-08-16 17:15:12.487440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1d624af8be'
down_revision: Union[str, Sequence[str], None] = '64d99c8b985d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stops', sa.Column('is_important', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('stops', sa.Column('is_optional', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stops', 'is_optional')
    op.drop_column('stops', 'is_important')
    # ### end Alembic commands ###
