"""allow multiple share links per permission

Revision ID: 8748a701b677
Revises: 79741effb0cf
Create Date: 2026-08-05 21:07:58.408945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8748a701b677'
down_revision: Union[str, Sequence[str], None] = '79741effb0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_trip_share_link_permission'), 'trip_share_links', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_trip_share_link_permission'), 'trip_share_links', ['trip_id', 'permission'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
