"""add directions_use_current_location to users

Revision ID: 928c5752d283
Revises: 9b634e94c902
Create Date: 2026-08-27 21:13:33.465741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928c5752d283'
down_revision: Union[str, Sequence[str], None] = '9b634e94c902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('directions_use_current_location', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'directions_use_current_location')
    # ### end Alembic commands ###
