"""share links expire in 24h, created_at is timezone-aware

Revision ID: d25b1fde590a
Revises: 8748a701b677
Create Date: 2026-08-05 22:49:18.163060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd25b1fde590a'
down_revision: Union[str, Sequence[str], None] = '8748a701b677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Explicit USING clause rather than relying on Postgres's default cast,
    # which reinterprets the naive value using the connection's `TIMEZONE`
    # setting - that's UTC on most managed Postgres hosts, but not
    # guaranteed everywhere, and every naive value written so far (via
    # `func.now()`) actually is UTC regardless of session setting.
    op.alter_column('trip_share_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="created_at AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip_share_links', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
