"""add stop categories

Revision ID: e9ec34daff92
Revises: 36db9ab9fa52
Create Date: 2026-09-30 01:31:49.218127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ec34daff92'
down_revision: Union[str, Sequence[str], None] = '36db9ab9fa52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stop_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stops', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stops', 'stop_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stops', type_='foreignkey')
    op.drop_column('stops', 'category_id')
    op.drop_table('stop_categories')
    # ### end Alembic commands ###
